In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv(
    "../data/raw/Superstore.csv",
    encoding="cp1252"
)

In [14]:
print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 9994
Columns: 21

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

Get a clean column list

In [16]:
for i, column in enumerate(df.columns, start=1):
    print(i, "→", column)

1 → Row ID
2 → Order ID
3 → Order Date
4 → Ship Date
5 → Ship Mode
6 → Customer ID
7 → Customer Name
8 → Segment
9 → Country
10 → City
11 → State
12 → Postal Code
13 → Region
14 → Product ID
15 → Category
16 → Sub-Category
17 → Product Name
18 → Sales
19 → Quantity
20 → Discount
21 → Profit

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,9994.0,4997.500000,2885.163629,1.000,2499.25000,4997.5000,7495.750,9994.000
Postal Code,9994.0,55190.379428,32063.693350,1040.000,23223.00000,56430.5000,90008.000,99301.000
Sales,9994.0,229.858001,623.245101,0.444,17.28000,54.4900,209.940,22638.480
Quantity,9994.0,3.789574,2.225110,1.000,2.00000,3.0000,5.000,14.000
Discount,9994.0,0.156203,0.206452,0.000,0.00000,0.2000,0.200,0.800
Profit,9994.0,28.656896,234.260108,-6599.978,1.72875,8.6665,29.364,8399.976

In [20]:
categorical_columns = df.select_dtypes(include="str").columns

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print("Unique values:", df[column].nunique())
    print(df[column].unique()[:20])

--- Order ID ---
Unique values: 5009
<StringArray>
['CA-2016-152156', 'CA-2016-138688', 'US-2015-108966', 'CA-2014-115812',
 'CA-2017-114412', 'CA-2016-161389', 'US-2015-118983', 'CA-2014-105893',
 'CA-2014-167164', 'CA-2014-143336', 'CA-2016-137330', 'US-2017-156909',
 'CA-2015-106320', 'CA-2016-121755', 'US-2015-150630', 'CA-2017-107727',
 'CA-2016-117590', 'CA-2015-117415', 'CA-2017-120999', 'CA-2016-101343']
Length: 20, dtype: str

--- Order Date ---
Unique values: 1237
<StringArray>
[ '11/8/2016',  '6/12/2016', '10/11/2015',   '6/9/2014',  '4/15/2017',
  '12/5/2016', '11/22/2015', '11/11/2014',  '5/13/2014',  '8/27/2014',
  '12/9/2016',  '7/16/2017',  '9/25/2015',  '1/16/2016',  '9/17/2015',
 '10/19/2017',  '12/8/2016', '12/27/2015',  '9/10/2017',  '7/17/2016']
Length: 20, dtype: str

--- Ship Date ---
Unique values: 1334
<StringArray>
['11/11/2016',  '6/16/2016', '10/18/2015',  '6/14/2014',  '4/20/2017',
 '12/10/2016', '11/26/2015', '11/18/2014',  '5/15/2014',   '9/1/2014',
 '12/13/2016',  '7/18/2017',  '9/30/2015',  '1/20/2016',  '9/21/2015',
 '10/23/2017', '12/31/2015',  '9/15/2017',  '7/22/2016',  '9/23/2017']
Length: 20, dtype: str

--- Ship Mode ---
Unique values: 4
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

--- Customer ID ---
Unique values: 793
<StringArray>
['CG-12520', 'DV-13045', 'SO-20335', 'BH-11710', 'AA-10480', 'IM-15070',
 'HP-14815', 'PK-19075', 'AG-10270', 'ZD-21925', 'KB-16585', 'SF-20065',
 'EB-13870', 'EH-13945', 'TB-21520', 'MA-17560', 'GH-14485', 'SN-20710',
 'LC-16930', 'RA-19885']
Length: 20, dtype: str

--- Customer Name ---
Unique values: 793
<StringArray>
[       'Claire Gute',    'Darrin Van Huff',     'Sean O'Donnell',
    'Brosina Hoffman',       'Andrew Allen',       'Irene Maddox',
      'Harold Pawlan',          'Pete Kriz',    'Alejandro Grove',
 'Zuschuss Donatelli',          'Ken Black',    'Sandra Flanagan',
        'Emily Burns',      'Eric Hoffmann',    'Tracy Blumstein',
       'Matt Abelman',          'Gene Hale',       'Steve Nguyen',
     'Linda Cazamias',       'Ruben Ausman']
Length: 20, dtype: str

--- Segment ---
Unique values: 3
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

--- Country ---
Unique values: 1
<StringArray>
['United States']
Length: 1, dtype: str

--- City ---
Unique values: 531
<StringArray>
[      'Henderson',     'Los Angeles', 'Fort Lauderdale',         'Concord',
         'Seattle',      'Fort Worth',         'Madison',     'West Jordan',
   'San Francisco',         'Fremont',    'Philadelphia',            'Orem',
         'Houston',      'Richardson',      'Naperville',       'Melbourne',
           'Eagan',        'Westland',           'Dover',      'New Albany']
Length: 20, dtype: str

--- State ---
Unique values: 49
<StringArray>
[      'Kentucky',     'California',        'Florida', 'North Carolina',
     'Washington',          'Texas',      'Wisconsin',           'Utah',
       'Nebraska',   'Pennsylvania',       'Illinois',      'Minnesota',
       'Michigan',       'Delaware',        'Indiana',       'New York',
        'Arizona',       'Virginia',      'Tennessee',        'Alabama']
Length: 20, dtype: str

--- Region ---
Unique values: 4
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

--- Product ID ---
Unique values: 1862
<StringArray>
['FUR-BO-10001798', 'FUR-CH-10000454', 'OFF-LA-10000240', 'FUR-TA-10000577',
 'OFF-ST-10000760', 'FUR-FU-10001487', 'OFF-AR-10002833', 'TEC-PH-10002275',
 'OFF-BI-10003910', 'OFF-AP-10002892', 'FUR-TA-10001539', 'TEC-PH-10002033',
 'OFF-PA-10002365', 'OFF-BI-10003656', 'OFF-AP-10002311', 'OFF-BI-10000756',
 'OFF-ST-10004186', 'OFF-ST-10000107', 'OFF-AR-10003056', 'TEC-PH-10001949']
Length: 20, dtype: str

--- Category ---
Unique values: 3
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

--- Sub-Category ---
Unique values: 17
<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

--- Product Name ---
Unique values: 1850
<StringArray>
[                                           'Bush Somerset Collection Bookcase',
                  'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
                    'Self-Adhesive Address Labels for Typewriters by Universal',
                                'Bretford CR4500 Series Slim Rectangular Table',
                                               'Eldon Fold 'N Roll Cart System',
             'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood',
                                                                   'Newell 322',
                                               'Mitel 5320 IP Phone VoIP phone',
                         'DXL Angle-View Binders with Locking Rings by Samsill',
                                             'Belkin F5C206VTEL 6 Outlet Surge',
                                     'Chromcraft Rectangular Conference Tables',
                                'Konftel 250 Conference phone - Charcoal black',
                                                                   'Xerox 1967',
                                  'Fellowes PB200 Plastic Comb Binding Machine',
 'Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter',
                             'Storex DuraTech Recycled Plastic Frosted Binders',
               'Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x 36"W x 18 1/2"D',
                                                   'Fellowes Super Stor/Drawer',
                                                                   'Newell 341',
                                                      'Cisco SPA 501G IP Phone']
Length: 20, dtype: str

In [21]:
product_check = df.groupby("Product ID")["Product Name"].nunique()

product_check[product_check > 1]

Product ID
FUR-BO-10002213    2
FUR-CH-10001146    2
FUR-FU-10001473    2
FUR-FU-10004017    2
FUR-FU-10004091    2
FUR-FU-10004270    2
FUR-FU-10004848    2
FUR-FU-10004864    2
OFF-AP-10000576    2
OFF-AR-10001149    2
OFF-BI-10002026    2
OFF-BI-10004632    2
OFF-BI-10004654    2
OFF-PA-10000357    2
OFF-PA-10000477    2
OFF-PA-10000659    2
OFF-PA-10001166    2
OFF-PA-10001970    2
OFF-PA-10002195    2
OFF-PA-10002377    2
OFF-PA-10003022    2
OFF-ST-10001228    2
OFF-ST-10004950    2
TEC-AC-10002049    2
TEC-AC-10002550    2
TEC-AC-10003832    2
TEC-MA-10001148    2
TEC-PH-10001530    2
TEC-PH-10001795    2
TEC-PH-10002200    2
TEC-PH-10002310    2
TEC-PH-10004531    2
Name: Product Name, dtype: int64

In [22]:
product_name_check = df.groupby("Product Name")["Product ID"].nunique()

product_name_check[product_name_check > 1]

Product Name
#10- 4 1/8" x 9 1/2" Recycled Envelopes           2
Avery Non-Stick Binders                           2
Easy-staple paper                                 8
Eldon Wave Desk Accessories                       2
KI Adjustable-Height Table                        2
Okidata C610n Printer                             2
Peel & Seel Recycled Catalog Envelopes, Brown     2
Prang Drawing Pencil Set                          2
Staple envelope                                   9
Staple holder                                     3
Staple magnet                                     2
Staple remover                                    3
Staple-based wall hangings                        2
Staples                                          10
Staples in misc. colors                           7
Storex Dura Pro Binders                           2
Name: Product ID, dtype: int64

In [25]:
df[df["Product ID"] == "FUR-BO-10002213"][
    ["Product ID", "Product Name", "Category", "Sub-Category"]
].drop_duplicates()

,Product ID,Product Name,Category,Sub-Category
2115,FUR-BO-10002213,DMI Eclipse Executive Suite Bookcases,Furniture,Bookcases
2471,FUR-BO-10002213,"Sauder Forest Hills Library, Woodland Oak Finish",Furniture,Bookcases

In [26]:
df[df["Product Name"] == "Staples"][
    ["Product ID", "Product Name", "Category", "Sub-Category"]
].drop_duplicates()

           Product ID Product Name         Category Sub-Category
132   OFF-FA-10002780      Staples  Office Supplies    Fasteners
525   OFF-FA-10002815      Staples  Office Supplies    Fasteners
646   OFF-FA-10003112      Staples  Office Supplies    Fasteners
1108  OFF-FA-10003495      Staples  Office Supplies    Fasteners
1147  OFF-FA-10000735      Staples  Office Supplies    Fasteners
1485  OFF-FA-10003021      Staples  Office Supplies    Fasteners
1703  OFF-FA-10001843      Staples  Office Supplies    Fasteners
2059  OFF-FA-10002975      Staples  Office Supplies    Fasteners
2387  OFF-FA-10001229      Staples  Office Supplies    Fasteners
4958  OFF-FA-10003485      Staples  Office Supplies    Fasteners

In [27]:
print("Order Date range:")
print(df["Order Date"].min(), "→", df["Order Date"].max())

print("\nShip Date range:")
print(df["Ship Date"].min(), "→", df["Ship Date"].max())

Order Date range:
1/1/2017 → 9/9/2017

Ship Date range:
1/1/2015 → 9/9/2017

In [28]:
date_check = df[["Order Date", "Ship Date"]].copy()

date_check["Order Date"] = pd.to_datetime(date_check["Order Date"])
date_check["Ship Date"] = pd.to_datetime(date_check["Ship Date"])

date_check["Shipping Days"] = (
    date_check["Ship Date"] - date_check["Order Date"]
).dt.days

date_check["Shipping Days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

In [29]:
date_check[date_check["Shipping Days"] < 0]

Empty DataFrame
Columns: [Order Date, Ship Date, Shipping Days]
Index: []

In [30]:
date_check["Order Date"] = pd.to_datetime(
    date_check["Order Date"],
    format="%m/%d/%Y"
)

date_check["Ship Date"] = pd.to_datetime(
    date_check["Ship Date"],
    format="%m/%d/%Y"
)

In [31]:
print("Actual Order Date range:")
print(date_check["Order Date"].min(), "→", date_check["Order Date"].max())

print("\nActual Ship Date range:")
print(date_check["Ship Date"].min(), "→", date_check["Ship Date"].max())

Actual Order Date range:
2014-01-03 00:00:00 → 2017-12-30 00:00:00

Actual Ship Date range:
2014-01-07 00:00:00 → 2018-01-05 00:00:00

In [32]:
print("\nInvalid shipping dates:")
print((date_check["Shipping Days"] < 0).sum())

Invalid shipping dates:
0

In [33]:
print("\nShipping mode vs zero-day shipments:")
print(
    pd.crosstab(
        df["Ship Mode"],
        date_check["Shipping Days"] == 0
    )
)

Shipping mode vs zero-day shipments:
Shipping Days   False  True
Ship Mode
First Class      1538      0
Same Day           24    519
Second Class     1945      0
Standard Class   5968      0

1st clean DF

In [35]:
df_clean = df.copy()

print("Raw shape:    ", df.shape)
print("Clean shape:  ", df_clean.shape)

Raw shape:     (9994, 21)
Clean shape:   (9994, 21)

In [36]:
df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    format="%m/%d/%Y"
)

df_clean["Ship Date"] = pd.to_datetime(
    df_clean["Ship Date"],
    format="%m/%d/%Y"
)

In [37]:
df_clean[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [38]:
df_clean["Shipping Days"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

In [39]:
df_clean["Shipping Days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

In [40]:
df_clean[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

In [41]:
print("Negative shipping days:", (df_clean["Shipping Days"] < 0).sum())
print("Maximum shipping days:", df_clean["Shipping Days"].max())
print("Minimum shipping days:", df_clean["Shipping Days"].min())

Negative shipping days: 0
Maximum shipping days: 7
Minimum shipping days: 0

In [43]:
df_clean[df_clean["Quantity"] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Days]
Index: []

[0 rows x 22 columns]

In [44]:
(df_clean["Quantity"] <= 0).sum()

np.int64(0)

In [45]:
df_clean[
    (df_clean["Discount"] < 0) |
    (df_clean["Discount"] > 1)
]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Days]
Index: []

[0 rows x 22 columns]

In [46]:
(df_clean["Sales"] < 0).sum()

np.int64(0)

In [47]:
negative_profit = df_clean[df_clean["Profit"] < 0]

print("Loss-making transactions:", len(negative_profit))
print(
    "Percentage of transactions:",
    round(len(negative_profit) / len(df_clean) * 100, 2),
    "%"
)

Loss-making transactions: 1871
Percentage of transactions: 18.72 %

In [48]:
(df_clean["Profit"] == 0).sum()

np.int64(65)

**LARGEST SALES TRANSACTION**

In [49]:
top_sales = df_clean.nlargest(10, "Sales")

top_sales[
    [
        "Order ID",
        "Customer Name",
        "Product Name",
        "Category",
        "Sales",
        "Quantity",
        "Discount",
        "Profit"
    ]
]

,Order ID,Customer Name,Product Name,Category,Sales,Quantity,Discount,Profit
2697,CA-2014-145317,Sean Miller,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,6,0.5,-1811.0784
6826,CA-2016-118689,Tamara Chand,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,5,0.0,8399.9760
8153,CA-2017-140151,Raymond Buch,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,4,0.0,6719.9808
2623,CA-2017-127180,Tom Ashbrook,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,4,0.2,3919.9888
4190,CA-2017-166709,Hunter Lopez,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,3,0.0,5039.9856
9039,CA-2016-117121,Adrian Barton,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,13,0.0,4946.3700
4098,CA-2014-116904,Sanjit Chand,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,5,0.0,4630.4755
4277,US-2016-107440,Bill Shonely,"3D Systems Cube Printer, 2nd Generation, Magenta",Technology,9099.930,7,0.0,2365.9818
8488,CA-2016-158841,Sanjit Engle,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,5,0.0,2799.9840
6425,CA-2016-143714,Christopher Conant,Canon imageCLASS 2200 Advanced Copier,Technology,8399.976,4,0.4,1119.9968

**The largest losses**

In [50]:
largest_losses = df_clean.nsmallest(10, "Profit")

largest_losses[
    [
        "Order ID",
        "Customer Name",
        "Product Name",
        "Category",
        "Sales",
        "Quantity",
        "Discount",
        "Profit"
    ]
]

,Order ID,Customer Name,Product Name,Category,Sales,Quantity,Discount,Profit
7772,CA-2016-108196,Cindy Stewart,Cubify CubeX 3D Printer Double Head Print,Technology,4499.985,5,0.7,-6599.9780
683,US-2017-168116,Grant Thornton,Cubify CubeX 3D Printer Triple Head Print,Technology,7999.980,4,0.5,-3839.9904
9774,CA-2014-169019,Luke Foster,GBC DocuBind P400 Electric Binding System,Office Supplies,2177.584,8,0.8,-3701.8928
3011,CA-2017-134845,Sharelle Roach,Lexmark MX611dhe Monochrome Laser Printer,Technology,2549.985,5,0.7,-3399.9800
4991,US-2017-122714,Henry Goldwyn,Ibico EPK-21 Electric Binding System,Office Supplies,1889.990,5,0.8,-2929.4845
3151,CA-2015-147830,Natalie Fritzler,Cubify CubeX 3D Printer Double Head Print,Technology,1799.994,2,0.7,-2639.9912
5310,CA-2017-131254,Nathan Cano,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,1525.188,6,0.8,-2287.7820
9639,CA-2015-116638,Joseph Holt,Chromcraft Bull-Nose Wood Oval Conference Tabl...,Furniture,4297.644,13,0.4,-1862.3124
1199,CA-2016-130946,Zuschuss Carroll,GBC DocuBind P400 Electric Binding System,Office Supplies,1088.792,4,0.8,-1850.9464
2697,CA-2014-145317,Sean Miller,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,6,0.5,-1811.0784

In [51]:
largest_profits = df_clean.nlargest(10, "Profit")

largest_profits[
    [
        "Order ID",
        "Customer Name",
        "Product Name",
        "Category",
        "Sales",
        "Quantity",
        "Discount",
        "Profit"
    ]
]

,Order ID,Customer Name,Product Name,Category,Sales,Quantity,Discount,Profit
6826,CA-2016-118689,Tamara Chand,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,5,0.0,8399.9760
8153,CA-2017-140151,Raymond Buch,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,4,0.0,6719.9808
4190,CA-2017-166709,Hunter Lopez,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,3,0.0,5039.9856
9039,CA-2016-117121,Adrian Barton,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,13,0.0,4946.3700
4098,CA-2014-116904,Sanjit Chand,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,5,0.0,4630.4755
2623,CA-2017-127180,Tom Ashbrook,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,4,0.2,3919.9888
509,CA-2015-145352,Christopher Martinez,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,6354.950,5,0.0,3177.4750
8488,CA-2016-158841,Sanjit Engle,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,5,0.0,2799.9840
7666,US-2016-140158,Daniel Raglin,Hewlett Packard LaserJet 3310 Copier,Technology,5399.910,9,0.0,2591.9568
6520,CA-2017-138289,Andy Reiter,GBC DocuBind P400 Electric Binding System,Office Supplies,5443.960,4,0.0,2504.2216

In [52]:
df_clean["Profit Margin"] = (
    df_clean["Profit"] / df_clean["Sales"]
)

In [53]:
df_clean["Profit Margin"].describe()

count    9994.000000
mean        0.120314
std         0.466754
min        -2.750000
25%         0.075000
50%         0.270000
75%         0.362500
max         0.500000
Name: Profit Margin, dtype: float64

In [54]:
df_clean["Order Year"] = df_clean["Order Date"].dt.year

In [55]:
df_clean["Order Year"].value_counts().sort_index()

Order Year
2014    1993
2015    2102
2016    2587
2017    3312
Name: count, dtype: int64

In [56]:
df_clean["Order Month"] = df_clean["Order Date"].dt.month

In [57]:
df_clean["Order Month"].value_counts().sort_index()

Order Month
1      381
2      300
3      696
4      668
5      735
6      717
7      710
8      706
9     1383
10     819
11    1471
12    1408
Name: count, dtype: int64

In [58]:
kpi_summary = {
    "Total Sales": df_clean["Sales"].sum(),
    "Total Profit": df_clean["Profit"].sum(),
    "Total Quantity": df_clean["Quantity"].sum(),
    "Total Orders": df_clean["Order ID"].nunique(),
    "Total Customers": df_clean["Customer ID"].nunique(),
    "Total Products": df_clean["Product ID"].nunique()
}

kpi_summary

{'Total Sales': np.float64(2297200.8603),
 'Total Profit': np.float64(286397.0217),
 'Total Quantity': np.int64(37873),
 'Total Orders': 5009,
 'Total Customers': 793,
 'Total Products': 1862}

In [59]:
overall_margin = (
    df_clean["Profit"].sum() /
    df_clean["Sales"].sum()
)

print("Overall Profit Margin:", overall_margin)
print("Overall Profit Margin %:", round(overall_margin * 100, 2), "%")

Overall Profit Margin: 0.12467217240315605
Overall Profit Margin %: 12.47 %

In [60]:
yearly_performance = (
    df_clean
    .groupby("Order Year")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

yearly_performance["Profit Margin %"] = (
    yearly_performance["Profit"] /
    yearly_performance["Sales"] * 100
).round(2)

yearly_performance

   Order Year        Sales      Profit  Orders  Quantity  Profit Margin %
0        2014  484247.4981  49543.9741     969      7581            10.23
1        2015  470532.5090  61618.6037    1038      7979            13.10
2        2016  609205.5980  81795.1743    1315      9837            13.43
3        2017  733215.2552  93439.2696    1687     12476            12.74

In [61]:
category_performance = (
    df_clean
    .groupby("Category")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

category_performance["Profit Margin %"] = (
    category_performance["Profit"] /
    category_performance["Sales"] * 100
).round(2)

category_performance.sort_values(
    "Profit",
    ascending=False
)

,Category,Sales,Profit,Orders,Quantity,Profit Margin %
2,Technology,836154.0330,145454.9481,1544,6939,17.40
1,Office Supplies,719047.0320,122490.8008,3742,22906,17.04
0,Furniture,741999.7953,18451.2728,1764,8028,2.49

In [62]:
subcategory_performance = (
    df_clean
    .groupby(["Category", "Sub-Category"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

subcategory_performance["Profit Margin %"] = (
    subcategory_performance["Profit"] /
    subcategory_performance["Sales"] * 100
).round(2)

subcategory_performance.sort_values(
    "Profit",
    ascending=False
)

,Category,Sub-Category,Sales,Profit,Orders,Quantity,Profit Margin %
14,Technology,Copiers,149528.0300,55617.8249,68,234,37.20
16,Technology,Phones,330007.0540,44515.7306,814,3289,13.49
13,Technology,Accessories,167380.3180,41936.6357,718,2976,25.05
10,Office Supplies,Paper,78479.2060,34053.5693,1191,5178,43.39
6,Office Supplies,Binders,203412.7330,30221.7633,1316,5974,14.86
1,Furniture,Chairs,328449.1030,26590.1663,576,2356,8.10
11,Office Supplies,Storage,223843.6080,21278.8264,777,3158,9.51
4,Office Supplies,Appliances,107532.1610,18138.0054,451,1729,16.87
2,Furniture,Furnishings,91705.1640,13059.1436,877,3563,14.24
7,Office Supplies,Envelopes,16476.4020,6964.1767,249,906,42.27
5,Office Supplies,Art,27118.7920,6527.7870,731,3000,24.07
9,Office Supplies,Labels,12486.3120,5546.2540,346,1400,44.42
15,Technology,Machines,189238.6310,3384.7569,112,440,1.79
8,Office Supplies,Fasteners,3024.2800,949.5182,215,914,31.40
12,Office Supplies,Supplies,46673.5380,-1189.0995,187,647,-2.55
0,Furniture,Bookcases,114879.9963,-3472.5560,224,868,-3.02
3,Furniture,Tables,206965.5320,-17725.4811,307,1241,-8.56

In [63]:
df_clean["Discount Band"] = pd.cut(
    df_clean["Discount"],
    bins=[-0.01, 0, 0.2, 0.4, 0.6, 0.8],
    labels=[
        "0%",
        "1-20%",
        "21-40%",
        "41-60%",
        "61-80%"
    ]
)

discount_analysis = (
    df_clean
    .groupby("Discount Band", observed=True)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

discount_analysis["Profit Margin %"] = (
    discount_analysis["Profit"] /
    discount_analysis["Sales"] * 100
).round(2)

discount_analysis

  Discount Band         Sales       Profit  Orders  Quantity  Profit Margin %
0            0%  1.087908e+06  320987.6032    2644     18267            29.51
1         1-20%  8.465222e+05  100785.4745    2507     14231            11.91
2        21-40%  2.341379e+05  -35817.4655     400      1740           -15.30
3        41-60%  7.104821e+04  -28944.1944     195       787           -40.74
4        61-80%  5.758404e+04  -70614.3961     594      2848          -122.63

In [64]:
discount_subcategory = (
    df_clean
    .groupby(["Sub-Category", "Discount Band"], observed=True)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
    .reset_index()
)

discount_subcategory["Profit Margin %"] = (
    discount_subcategory["Profit"] /
    discount_subcategory["Sales"] * 100
).round(2)

discount_subcategory

,Sub-Category,Discount Band,Sales,Profit,Orders,Profit Margin %
0,Accessories,0%,118370.3100,35289.2539,435,29.81
1,Accessories,1-20%,49010.0080,6647.3818,283,13.56
2,Appliances,0%,78066.1900,23183.7361,265,29.70
3,Appliances,1-20%,26083.4370,3583.9105,121,13.74
4,Appliances,61-80%,3382.5340,-8629.6412,65,-255.12
5,Art,0%,18014.6400,5380.6006,452,29.87
6,Art,1-20%,9104.1520,1147.1864,279,12.60
7,Binders,0%,81829.4800,39314.4507,295,48.04
8,Binders,1-20%,85442.6400,29417.8090,495,34.43
9,Binders,61-80%,36140.6130,-38510.4964,526,-106.56
10,Bookcases,0%,31935.9800,6075.7117,60,19.02
11,Bookcases,1-20%,54400.0175,1549.4937,95,2.85
12,Bookcases,21-40%,18776.1568,-2947.0103,36,-15.70
13,Bookcases,41-60%,7308.4600,-4255.8117,18,-58.23
14,Bookcases,61-80%,2459.3820,-3894.9394,15,-158.37
15,Chairs,0%,91060.7300,21933.0961,124,24.09
16,Chairs,1-20%,167382.8710,11394.1869,303,6.81
17,Chairs,21-40%,70005.5020,-6737.1167,149,-9.62
18,Copiers,0%,76449.1800,35556.1349,22,46.51
19,Copiers,1-20%,56159.0480,17878.7148,37,31.84
20,Copiers,21-40%,16919.8020,2182.9752,9,12.90
21,Envelopes,0%,10606.4500,4976.9844,148,46.92
22,Envelopes,1-20%,5869.9520,1987.1923,101,33.85
23,Fasteners,0%,1822.8400,652.2052,128,35.78
24,Fasteners,1-20%,1201.4400,297.3130,87,24.75
25,Furnishings,0%,61449.8000,16847.9689,529,27.42
26,Furnishings,1-20%,23610.6640,2155.8299,221,9.13
27,Furnishings,41-60%,6644.7000,-5944.6552,127,-89.46
28,Labels,0%,9239.5600,4422.0960,225,47.86
29,Labels,1-20%,3246.7520,1124.1580,121,34.62
30,Machines,0%,71034.0000,27137.8223,29,38.20
31,Machines,1-20%,41365.5230,5802.2867,33,14.03
32,Machines,21-40%,23302.5290,-2340.8039,17,-10.05
33,Machines,41-60%,37935.0700,-7635.2291,11,-20.13
34,Machines,61-80%,15601.5090,-19579.3191,22,-125.50
35,Paper,0%,53157.8700,25329.4677,737,47.65
36,Paper,1-20%,25321.3360,8724.1016,454,34.45
37,Phones,0%,123879.7100,34365.2093,278,27.74
38,Phones,1-20%,171789.9920,16536.3067,438,9.63
39,Phones,21-40%,34337.3520,-6385.7854,98,-18.60
40,Storage,0%,157853.7600,25528.1715,484,16.17
41,Storage,1-20%,65989.8480,-4249.3451,293,-6.44
42,Supplies,0%,31559.2100,1718.3942,115,5.44
43,Supplies,1-20%,15114.3280,-2907.4937,72,-19.24
44,Tables,0%,71578.7600,13276.2997,70,18.55
45,Tables,1-20%,45430.2320,-303.5580,69,-0.67
46,Tables,21-40%,70796.5560,-19589.7244,123,-27.67
47,Tables,41-60%,19159.9840,-11108.4984,45,-57.98

**Find the products responsible for the largest losses**

In [65]:
product_profit = (
    df_clean
    .groupby(["Product ID", "Product Name"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum"),
        Orders=("Order ID", "nunique"),
        Avg_Discount=("Discount", "mean")
    )
    .reset_index()
)

loss_products = (
    product_profit[product_profit["Profit"] < 0]
    .sort_values("Profit")
    .head(15)
)

loss_products

,Product ID,Product Name,Sales,Profit,Quantity,Orders,Avg_Discount
1645,TEC-MA-10000418,Cubify CubeX 3D Printer Double Head Print,11099.963,-8879.9704,9,3,0.533333
1650,TEC-MA-10000822,Lexmark MX611dhe Monochrome Laser Printer,16829.901,-4589.9730,18,4,0.400000
1696,TEC-MA-10004125,Cubify CubeX 3D Printer Triple Head Print,7999.980,-3839.9904,4,1,0.500000
326,FUR-TA-10000198,Chromcraft Bull-Nose Wood Oval Conference Tabl...,9917.640,-2876.1156,27,5,0.280000
344,FUR-TA-10001889,Bush Advantage Collection Racetrack Conference...,9544.725,-1934.3976,33,7,0.350000
858,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,17965.068,-1878.1662,27,6,0.450000
1669,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,22638.480,-1811.0784,6,1,0.500000
1465,OFF-SU-10002881,Martin Yale Chadless Opener Electric Letter Op...,16656.200,-1299.1836,22,6,0.100000
346,FUR-TA-10001950,Balt Solid Wood Round Tables,6518.754,-1201.0581,19,4,0.200000
375,FUR-TA-10004289,BoxOffice By Design Rectangular and Half-Moon ...,1706.250,-1148.4375,15,3,0.483333
372,FUR-TA-10004154,"Riverside Furniture Oval Coffee Table, Oval En...",4446.175,-1147.4000,25,5,0.300000
1668,TEC-MA-10002210,Epson TM-T88V Direct Thermal Printer - Monochr...,1212.705,-1057.2300,10,2,0.550000
105,FUR-CH-10003312,Hon 2090 “Pillow Soft” Series Mid Back Swivel/...,5282.424,-989.0496,24,6,0.216667
15,FUR-BO-10001972,O'Sullivan 4-Shelf Bookcase in Odessa Pine,2740.197,-975.0988,37,7,0.421429
374,FUR-TA-10004256,Bretford “Just In Time” Height-Adjustable Mult...,5634.900,-964.1940,17,4,0.225000

In [66]:
worst_transactions = (
    df_clean[
        [
            "Order ID",
            "Order Date",
            "Customer Name",
            "Product ID",
            "Product Name",
            "Category",
            "Sub-Category",
            "Sales",
            "Quantity",
            "Discount",
            "Profit"
        ]
    ]
    .sort_values("Profit")
    .head(20)
)

worst_transactions

,Order ID,Order Date,Customer Name,Product ID,Product Name,Category,Sub-Category,Sales,Quantity,Discount,Profit
7772,CA-2016-108196,2016-11-25,Cindy Stewart,TEC-MA-10000418,Cubify CubeX 3D Printer Double Head Print,Technology,Machines,4499.985,5,0.7,-6599.9780
683,US-2017-168116,2017-11-04,Grant Thornton,TEC-MA-10004125,Cubify CubeX 3D Printer Triple Head Print,Technology,Machines,7999.980,4,0.5,-3839.9904
9774,CA-2014-169019,2014-07-26,Luke Foster,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,Office Supplies,Binders,2177.584,8,0.8,-3701.8928
3011,CA-2017-134845,2017-04-17,Sharelle Roach,TEC-MA-10000822,Lexmark MX611dhe Monochrome Laser Printer,Technology,Machines,2549.985,5,0.7,-3399.9800
4991,US-2017-122714,2017-12-07,Henry Goldwyn,OFF-BI-10001120,Ibico EPK-21 Electric Binding System,Office Supplies,Binders,1889.990,5,0.8,-2929.4845
3151,CA-2015-147830,2015-12-15,Natalie Fritzler,TEC-MA-10000418,Cubify CubeX 3D Printer Double Head Print,Technology,Machines,1799.994,2,0.7,-2639.9912
5310,CA-2017-131254,2017-11-19,Nathan Cano,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,Binders,1525.188,6,0.8,-2287.7820
9639,CA-2015-116638,2015-01-28,Joseph Holt,FUR-TA-10000198,Chromcraft Bull-Nose Wood Oval Conference Tabl...,Furniture,Tables,4297.644,13,0.4,-1862.3124
1199,CA-2016-130946,2016-04-08,Zuschuss Carroll,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,Office Supplies,Binders,1088.792,4,0.8,-1850.9464
2697,CA-2014-145317,2014-03-18,Sean Miller,TEC-MA-10002412,Cisco TelePresence System EX90 Videoconferenci...,Technology,Machines,22638.480,6,0.5,-1811.0784
27,US-2015-150630,2015-09-17,Tracy Blumstein,FUR-BO-10004834,"Riverside Palais Royal Lawyers Bookcase, Royal...",Furniture,Bookcases,3083.430,7,0.5,-1665.0522
3324,CA-2014-165309,2014-11-11,Karen Daniels,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,Office Supplies,Binders,896.990,5,0.8,-1480.0335
165,CA-2014-139892,2014-09-08,Becky Martin,TEC-MA-10000822,Lexmark MX611dhe Monochrome Laser Printer,Technology,Machines,8159.952,8,0.4,-1359.9920
2928,US-2017-120390,2017-10-19,Tracy Hopkins,OFF-BI-10004995,GBC DocuBind P400 Electric Binding System,Office Supplies,Binders,1633.188,4,0.7,-1306.5504
7898,CA-2017-128363,2017-08-13,Dan Campbell,OFF-BI-10001359,GBC DocuBind TL300 Electric Binding System,Office Supplies,Binders,1614.582,6,0.7,-1237.8462
4820,CA-2015-140025,2015-04-07,Peter Fuller,OFF-AP-10002651,Hoover Upright Vacuum With Dirt Cup,Office Supplies,Appliances,463.248,8,0.8,-1181.2824
2846,CA-2017-152093,2017-09-10,Skye Norling,OFF-BI-10003527,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,Binders,762.594,3,0.8,-1143.8910
8640,US-2017-148551,2017-01-12,David Bremer,OFF-BI-10000545,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,Binders,760.980,5,0.8,-1141.4700
4355,CA-2015-155600,2015-12-04,Rose O'Brian,OFF-BI-10000545,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,Binders,1598.058,7,0.7,-1065.3720
1803,CA-2017-158379,2017-09-22,Joseph Airdo,OFF-SU-10002881,Martin Yale Chadless Opener Electric Letter Op...,Office Supplies,Supplies,4663.736,7,0.2,-1049.3406

In [67]:
discount_impact = discount_analysis.copy()

total_sales = df_clean["Sales"].sum()

discount_impact["Sales Share %"] = (
    discount_impact["Sales"] /
    total_sales * 100
).round(2)

discount_impact["Profit Contribution %"] = (
    discount_impact["Profit"] /
    df_clean["Profit"].sum() * 100
).round(2)

discount_impact

,Discount Band,Sales,Profit,Orders,Quantity,Profit Margin %,Sales Share %,Profit Contribution %
0,0%,1.087908e+06,320987.6032,2644,18267,29.51,47.36,112.08
1,1-20%,8.465222e+05,100785.4745,2507,14231,11.91,36.85,35.19
2,21-40%,2.341379e+05,-35817.4655,400,1740,-15.30,10.19,-12.51
3,41-60%,7.104821e+04,-28944.1944,195,787,-40.74,3.09,-10.11
4,61-80%,5.758404e+04,-70614.3961,594,2848,-122.63,2.51,-24.66

In [68]:
customer_performance = (
    df_clean
    .groupby(["Customer ID", "Customer Name", "Segment"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

customer_performance["Profit Margin %"] = (
    customer_performance["Profit"] /
    customer_performance["Sales"] * 100
).round(2)

customer_performance.sort_values(
    "Sales",
    ascending=False
).head(20)

,Customer ID,Customer Name,Segment,Sales,Profit,Orders,Quantity,Profit Margin %
700,SM-20320,Sean Miller,Home Office,25043.050,-1980.7393,5,50,-7.91
741,TC-20980,Tamara Chand,Corporate,19052.218,8981.3239,5,42,47.14
621,RB-19360,Raymond Buch,Consumer,15117.339,6976.0959,6,71,46.15
730,TA-21385,Tom Ashbrook,Home Office,14595.620,4703.7883,4,36,32.23
6,AB-10105,Adrian Barton,Consumer,14473.571,5444.8055,10,73,37.62
434,KL-16645,Ken Lonsdale,Consumer,14175.229,806.8550,12,113,5.69
669,SC-20095,Sanjit Chand,Consumer,14142.334,5757.4119,9,87,40.71
327,HL-15040,Hunter Lopez,Consumer,12873.298,5622.4292,6,50,43.68
683,SE-20110,Sanjit Engle,Consumer,12209.438,2650.6769,11,78,21.71
131,CC-12370,Christopher Conant,Consumer,12129.072,2177.0493,5,34,17.95
764,TS-21370,Todd Sumrall,Corporate,11891.751,2371.7144,6,59,19.94
311,GT-14710,Greg Tran,Consumer,11820.120,2163.4269,11,106,18.30
90,BM-11140,Becky Martin,Consumer,11789.630,-1659.9581,4,64,-14.08
720,SV-20365,Seth Vernon,Consumer,11470.950,1199.4242,10,109,10.46
146,CJ-12010,Caroline Jumper,Consumer,11164.974,858.7414,8,83,7.69
152,CL-12565,Clay Ludtke,Consumer,10880.546,1933.7831,12,106,17.77
497,ME-17320,Maria Etezadi,Home Office,10663.728,1859.4695,10,82,17.44
427,KF-16285,Karen Ferguson,Home Office,10604.266,1660.1386,7,67,15.66
104,BS-11365,Bill Shonely,Corporate,10501.653,2616.0644,5,39,24.91
257,EH-13765,Edward Hooks,Corporate,10310.880,1393.5154,12,120,13.51

In [69]:
customer_performance.sort_values(
    "Profit",
    ascending=False
).head(20)

,Customer ID,Customer Name,Segment,Sales,Profit,Orders,Quantity,Profit Margin %
741,TC-20980,Tamara Chand,Corporate,19052.2180,8981.3239,5,42,47.14
621,RB-19360,Raymond Buch,Consumer,15117.3390,6976.0959,6,71,46.15
669,SC-20095,Sanjit Chand,Consumer,14142.3340,5757.4119,9,87,40.71
327,HL-15040,Hunter Lopez,Consumer,12873.2980,5622.4292,6,50,43.68
6,AB-10105,Adrian Barton,Consumer,14473.5710,5444.8055,10,73,37.62
730,TA-21385,Tom Ashbrook,Home Office,14595.6200,4703.7883,4,36,32.23
160,CM-12385,Christopher Martinez,Consumer,8954.0200,3899.8904,4,34,43.55
424,KD-16495,Keith Dawkins,Corporate,8181.2560,3038.6254,12,84,37.14
48,AR-10540,Andy Reiter,Consumer,6608.4480,2884.6208,6,33,43.65
234,DR-12940,Daniel Raglin,Home Office,8350.8680,2869.0760,8,57,34.36
737,TB-21400,Tom Boeckenhauer,Consumer,9133.9900,2798.3689,7,55,30.64
568,NM-18445,Nathan Mautz,Home Office,6459.3440,2751.6849,7,44,42.60
683,SE-20110,Sanjit Engle,Consumer,12209.4380,2650.6769,11,78,21.71
104,BS-11365,Bill Shonely,Corporate,10501.6530,2616.0644,5,39,24.91
328,HM-14860,Harry Marie,Corporate,8236.7648,2437.9836,10,76,29.60
764,TS-21370,Todd Sumrall,Corporate,11891.7510,2371.7144,6,59,19.94
92,BM-11650,Brian Moss,Corporate,7294.1850,2199.2781,11,95,30.15
131,CC-12370,Christopher Conant,Consumer,12129.0720,2177.0493,5,34,17.95
410,JW-15220,Jane Waco,Corporate,7721.7140,2173.7094,6,66,28.15
333,HW-14935,Helen Wasserman,Corporate,9300.2540,2164.1611,8,85,23.27

In [70]:
segment_performance = (
    df_clean
    .groupby("Segment")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Customers=("Customer ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

segment_performance["Profit Margin %"] = (
    segment_performance["Profit"] /
    segment_performance["Sales"] * 100
).round(2)

segment_performance["Avg Order Value"] = (
    segment_performance["Sales"] /
    segment_performance["Orders"]
).round(2)

segment_performance

,Segment,Sales,Profit,Orders,Customers,Quantity,Profit Margin %,Avg Order Value
0,Consumer,1.161401e+06,134119.2092,2586,409,19521,11.55,449.11
1,Corporate,7.061464e+05,91979.1340,1514,236,11608,13.03,466.41
2,Home Office,4.296531e+05,60298.6785,909,148,6744,14.03,472.67

In [71]:
region_performance = (
    df_clean
    .groupby("Region")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Customers=("Customer ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

region_performance["Profit Margin %"] = (
    region_performance["Profit"] /
    region_performance["Sales"] * 100
).round(2)

region_performance["Avg Order Value"] = (
    region_performance["Sales"] /
    region_performance["Orders"]
).round(2)

region_performance.sort_values(
    "Sales",
    ascending=False
)

,Region,Sales,Profit,Orders,Customers,Quantity,Profit Margin %,Avg Order Value
3,West,725457.8245,108418.4489,1611,686,12266,14.94,450.32
1,East,678781.2400,91522.7800,1401,674,10618,13.48,484.50
0,Central,501239.8908,39706.3625,1175,629,8780,7.92,426.59
2,South,391721.9050,46749.4303,822,512,6209,11.93,476.55

In [72]:
monthly_performance = (
    df_clean
    .groupby(["Order Year", "Order Month"])
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique")
    )
    .reset_index()
)

monthly_performance["Profit Margin %"] = (
    monthly_performance["Profit"] /
    monthly_performance["Sales"] * 100
).round(2)

monthly_performance

    Order Year  Order Month        Sales      Profit  Orders  Profit Margin %
0         2014            1   14236.8950   2450.1907      32            17.21
1         2014            2    4519.8920    862.3084      28            19.08
2         2014            3   55691.0090    498.7299      71             0.90
3         2014            4   28295.3450   3488.8352      66            12.33
4         2014            5   23648.2870   2738.7096      69            11.58
5         2014            6   34595.1276   4976.5244      66            14.39
6         2014            7   33946.3930   -841.4826      65            -2.48
7         2014            8   27909.4685   5318.1050      72            19.05
8         2014            9   81777.3508   8328.0994     130            10.18
9         2014           10   31453.3930   3448.2573      78            10.96
10        2014           11   78628.7167   9292.1269     151            11.82
11        2014           12   69545.6205   8983.5699     141            12.92
12        2015            1   18174.0756  -3281.0070      29           -18.05
13        2015            2   11951.4110   2813.8508      36            23.54
14        2015            3   38726.2520   9732.0978      79            25.13
15        2015            4   34195.2085   4187.4962      72            12.25
16        2015            5   30131.6865   4667.8690      74            15.49
17        2015            6   24797.2920   3335.5572      68            13.45
18        2015            7   28765.3250   3288.6483      66            11.43
19        2015            8   36898.3322   5355.8084      68            14.52
20        2015            9   64595.9180   8209.1627     140            12.71
21        2015           10   31404.9235   2817.3660      87             8.97
22        2015           11   75972.5635  12474.7884     158            16.42
23        2015           12   74919.5212   8016.9659     161            10.70
24        2016            1   18542.4910   2824.8233      48            15.23
25        2016            2   22978.8150   5004.5795      45            21.78
26        2016            3   51715.8750   3611.9680      86             6.98
27        2016            4   38750.0390   2977.8149      89             7.68
28        2016            5   56987.7280   8662.1464     108            15.20
29        2016            6   40344.5340   4750.3781      97            11.77
30        2016            7   39261.9630   4432.8779      96            11.29
31        2016            8   31115.3743   2062.0693      90             6.63
32        2016            9   73410.0249   9328.6576     192            12.71
33        2016           10   59687.7450  16243.1425     105            27.21
34        2016           11   79411.9658   4011.4075     183             5.05
35        2016           12   96999.0430  17885.3093     176            18.44
36        2017            1   43971.3740   7140.4391      69            16.24
37        2017            2   20301.1334   1613.8720      53             7.95
38        2017            3   58872.3528  14751.8915     118            25.06
39        2017            4   36521.5361    933.2900     116             2.56
40        2017            5   44261.1102   6342.5828     118            14.33
41        2017            6   52981.7257   8223.3357     133            15.52
42        2017            7   45264.4160   6952.6212     111            15.36
43        2017            8   63120.8880   9040.9557     111            14.32
44        2017            9   87866.6520  10991.5556     226            12.51
45        2017           10   77776.9232   9275.2755     147            11.93
46        2017           11  118447.8250   9690.1037     261             8.18
47        2017           12   83829.3188   8483.3468     224            10.12

In [73]:
shipping_performance = (
    df_clean
    .groupby("Ship Mode")
    .agg(
        Orders=("Order ID", "nunique"),
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Avg_Shipping_Days=("Shipping Days", "mean"),
        Quantity=("Quantity", "sum")
    )
    .reset_index()
)

shipping_performance["Avg Shipping Days"] = (
    shipping_performance["Avg_Shipping_Days"]
    .round(2)
)

shipping_performance["Profit Margin %"] = (
    shipping_performance["Profit"] /
    shipping_performance["Sales"] * 100
).round(2)

shipping_performance.drop(
    columns=["Avg_Shipping_Days"]
)

,Ship Mode,Orders,Sales,Profit,Quantity,Avg Shipping Days,Profit Margin %
0,First Class,787,3.514284e+05,48969.8399,5693,2.18,13.93
1,Same Day,264,1.283631e+05,15891.7589,1960,0.04,12.38
2,Second Class,964,4.591936e+05,57446.6354,7423,3.24,12.51
3,Standard Class,2994,1.358216e+06,164088.7875,22797,5.01,12.08

In [74]:
correlation_data = df_clean[
    [
        "Sales",
        "Quantity",
        "Discount",
        "Profit",
        "Shipping Days"
    ]
].corr()

correlation_data.round(2)

               Sales  Quantity  Discount  Profit  Shipping Days
Sales           1.00      0.20     -0.03    0.48          -0.01
Quantity        0.20      1.00      0.01    0.07           0.02
Discount       -0.03      0.01      1.00   -0.22           0.00
Profit          0.48      0.07     -0.22    1.00          -0.00
Shipping Days  -0.01      0.02      0.00   -0.00           1.00

In [76]:
import os

os.makedirs("../data/processed", exist_ok=True)

df_final.to_csv(
    "../data/processed/retailpulse_clean.csv",
    index=False
)

print("Final analytical dataset created successfully!")
print("Rows:", len(df_final))
print("Columns:", len(df_final.columns))
print("File saved to: ../data/processed/retailpulse_clean.csv")

Final analytical dataset created successfully!
Rows: 9994
Columns: 25
File saved to: ../data/processed/retailpulse_clean.csv

In [77]:
final_columns = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "Shipping Days",
    "Ship Mode",
    "Customer ID",
    "Customer Name",
    "Segment",
    "Country",
    "City",
    "State",
    "Postal Code",
    "Region",
    "Product ID",
    "Product Name",
    "Category",
    "Sub-Category",
    "Sales",
    "Quantity",
    "Discount",
    "Profit",
    "Profit Margin",
    "Order Year",
    "Order Month"
]

df_final = df_clean[final_columns].copy()

df_final.to_csv(
    "../data/processed/retailpulse_clean.csv",
    index=False
)

print("Final analytical dataset created!")
print("Rows:", len(df_final))
print("Columns:", len(df_final.columns))

Final analytical dataset created!
Rows: 9994
Columns: 25